### ISSUE TITLE
Switch visibility if multiple files are open

### ISSUE THREAD

**Issue by uhelfenstein** [AstoCAD/FreeCAD#82]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

If I have multiple files open, it happens often when I click something or do an operation, that the visibility switches to the first file of the tabs.

### Full version info

```shell
OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.1.0dev.42836 (Git)
Build date: 2025/07/29 06:28:12
Build type: Release
Branch: AstoCAD
Hash: 214716b2833df45ffb7798a82ae557f870886fc6
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: German/Switzerland (de_CH)
Navigation Style/Orbit Style/Rotation Mode: TinkerCAD/Trackball/Object center
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/141.585/1
```

### Subproject(s) affected?

None

### Anything else?

https://github.com/user-attachments/assets/f5c7a7fc-1e4c-472b-8c7f-8d13d30ce4e3

In this screen recording you can see the issue. 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
I have experienced this bug in the past. However I was unable to replicate for a long time so I think that FreeCAD fixed it upstream. I'm a bit surprised that you experienced it with the build number 42836 though as I thought it was fixed sooner than that.
Can you still replicate in latest build?

**Comment by uhelfenstein** [comment]
Hi, I used the latest AstoCad version and I still see this effect. It is not all the time but I reproduced it with the example parts. My experience is that at the beginning it works but once this switching of parts happend it comes more regularly and sometimes with each operation which is annoying. 

<img width="524" height="616" alt="Image" src="https://github.com/user-attachments/assets/2012f0ac-d677-43a1-a371-1eab027d52d3" />

https://github.com/user-attachments/assets/23355414-09db-483c-8ff3-5c1550a558d3

**Comment by PaddleStroke** [comment]
I know this bug is infuriating as it myself drove me nuts. So sorry about this.
Do you perhaps know if the same happens in FreeCAD weekly builds or is this only in AstoCAD?

**Comment by PaddleStroke** [comment]
Have you tried to clear the preferences? I cannot replicate this on my side in 43302
Try deleting \AppData\Roaming\AstoCAD that will reset all preferences of AstoCAD.

**Comment by uhelfenstein** [comment]
> Have you tried to clear the preferences? I cannot replicate this on my side in 43302 Try deleting \AppData\Roaming\AstoCAD that will reset all preferences of AstoCAD.

You are rigtht. By renaming the AstoCAD folder in AppData, I cannot replicate it too. I changed the settings and it still did not appear anymore. Would you like to get some data of my former AstoCAD AppData folder to analyze or is it considered to be resolved?

**Comment by PaddleStroke** [comment]
Ah great ! If you can post the user.cfg file (in that folder) I can check and see which preference is triggering this bug.

**Comment by uhelfenstein** [comment]
> Ah great ! If you can post the user.cfg file (in that folder) I can check and see which preference is triggering this bug.

Sure, here is the user.cfg of the settigs I faced this issue:

[user.cfg.txt](https://github.com/user-attachments/files/22255265/user.cfg.txt)
